name: Build step


on:
  push:
    branches: 
     - prod
     - dev
  pull_request:
    branches: [ "main" ]


jobs:
  
  
   
   build-and-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/prod' && 'prod' || 'dev' }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
          

      - name: env file
        env:
          PROD_HOST: ${{ vars.PROD_HOST }}
          DEV_URL: ${{ vars.DEV_URL }}
          DEV_HOST: ${{ vars.DEV_HOST }}
          PROD_URL: ${{ vars.PROD_URL }}
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
           set -x
           
           bash ./script.sh 
          

      - name: afficher env 
        run: |
    
           cat .env
      
      

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME}}
          password:  ${{ secrets.DOCKER_PASSWORD }}
     
          
      - name: Build image and push to Docker Hub 
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            houwayda/ecom_front_${{ github.ref == 'refs/heads/prod' && 'prod' || 'dev' }}:${{ github.sha }}
          push: true

   update-kustomize-file-overrlays:
     if:  github.ref == 'refs/heads/prod'
     runs-on: ubuntu-latest
     needs: ['build-and-push-docker-image']
     steps:
      - name: Checkout another repository
        uses: actions/checkout@v2
        with:
          repository: houwayda9/ecom-kustomize
          ref: main
          token: ${{ secrets.G_TOKEN }}
          path: houwayda9/ecom-kustomize 
      
      - name: Update Kustomize file
        run: |
            case "${{ github.ref }}" in
             "refs/heads/dev")
              overlay_dir="dev"
              ;;
             "refs/heads/prod")
              overlay_dir="prod"
              ;;
              "refs/heads/main")
              overlay_dir="main"
              ;;
             *)
              echo "Unexpected branch: ${{ github.ref }}"
              exit 1
              ;;
            esac
            cd houwayda9/ecom-kustomize/kustomize/overlays/${overlay_dir}
            sed -i '/^images:$/,/^$/ { /- name: houwayda\/ecom-front/,/newTag:/ s/newTag: .*/newTag: ${{ github.sha }}/ }' kustomization.yaml
            git config --global user.email ${{ secrets.USER_EMAIL }}
            git config --global user.name ${{ secrets.USER_NAME }}
            git add kustomization.yaml
            git commit -m "Update image for - ${{ github.sha }}"
            git push origin main


            
