name: Build step

on:
  push:
    branches: 
     - main
     - dev
  pull_request:
    branches: [ "main" ]


jobs:
 
 build-and-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/prod' && 'prod' || 'dev' }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME}}
          password:  ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build image and push to Docker Hub 
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            houwayda/ecom_front_${{ github.ref == 'refs/heads/prod' && 'prod' || 'dev' }}:${{ github.sha }}
          push: true
 update-kustomize-file-overrlays:
     if: github.ref == 'refs/heads/dev'
     runs-on: ubuntu-latest
     needs: ['build-and-push-docker-image']
     steps:
      - name: Checkout another repository
        uses: actions/checkout@v2
        with:
          repository: houwayda9/ecom-kustomize
          ref: main
          token: ${{ secrets.G_TOKEN }}
          path: houwayda9/ecom-kustomize 
      - name: Debug
        run: |
         cd houwayda9/ecom-kustomize/kustomize
         ls -l  
         cd overlays/dev
         sed -i '/^images:$/,/^$/ { /- name: houwayda\/ecom-front/,/newTag:/ s/newTag: .*/newTag: ${{ github.sha }}/ }' kustomization.yaml
         cat kustomization.yaml
         ls -l
      - name: Update Kustomize file
        run: |
            pwd
            cd houwayda9/ecom-kustomize/kustomize/overlays/dev
            git config --global user.email ${{ secrets.USER_EMAIL }}
            git config --global user.name ${{ secrets.USER_NAME }}
            git add kustomization.yaml
            git commit -m "Update image for - ${{ github.sha }}"
            git push origin main
            
